### ISSUE TITLE
갑자기 API 호출이 안됩니다

### ISSUE THREAD

**Issue by EugeneJang** [navertalk/chatbot-api#130]
2017년도부터 사용하던 API가 갑자기 호출이 안되고 있습니다.

툴로 REST API 호출은 정상으로 되는데 서버에서 호출할때 이런에러가 떨어지네요

TLS 관련 변경되거나 업그레이드 해야할것이 있을까요?

확인부탁드립니다.

에러 내용입니다.
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://gw.talk.naver.com/chatbot/v1/event":sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:538) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:457) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at com.lgcns.obot.svc.common.service.RestInterfaceServiceImpl.requestRestIf(RestInterfaceServiceImpl.java:169) ~[RestInterfaceServiceImpl.class:na]
        ... 71 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by navertalk** [comment]
안녕하세요. 네이버 톡톡입니다.
먼저 사용에 문제가 생긴 점에 대해서 사과드립니다. 😭 
gw.talk.naver.com 에서 사용하는 인증서 체인의 루트 인증이 만료되어 발생한 현상입니다.
인증서 교체하였으니, 혹시 이슈 재발하는지 확인부탁드립니다.

**Comment by EugeneJang** [comment]
정상화 확인했습니다 아찔했네요😭

**Comment by navertalk** [comment]
네. 다시 한 번 불편을 드려 죄송합니다. 
그리고 제보 감사드립니다!
